# 2. Data Cleaning


## Overview

Tahap data cleaning dilakukan untuk memastikan dataset memiliki kualitas yang baik, konsisten, dan siap digunakan untuk proses analisis selanjutnya.

Pada tahap ini dilakukan identifikasi, investigasi, dan penanganan terhadap berbagai permasalahan kualitas data, seperti:

* Duplicate data
* Missing value
* Kesalahan data type
* Invalid value
* Outlier

Setiap permasalahan pada data tidak langsung dihapus atau diubah. Terlebih dahulu dilakukan investigasi untuk menentukan apakah data tersebut merupakan data yang valid atau merupakan kesalahan data.

### Data Cleaning Workflow

**Duplicate Detection**
↓
**Duplicate Investigation**
↓
**Duplicate Treatment**
↓
**Missing Value Detection**
↓
**Missing Value Investigation**
↓
**Missing Value Treatment**
↓
**Data Type Validation**
↓
**Data Type Conversion**
↓
**Invalid Value Detection**
↓
**Invalid Value Investigation**
↓
**Invalid Value Treatment**
↓
**Outlier Detection**
↓
**Outlier Investigation**
↓
**Outlier Treatment**
↓
**Data Validation**
↓
**Clean Dataset**

### Objective

Tujuan utama tahap data cleaning adalah:

1. Mengidentifikasi permasalahan pada dataset.
2. Menentukan apakah data yang bermasalah valid atau tidak.
3. Menangani data yang tidak sesuai dengan kebutuhan analisis.
4. Memastikan konsistensi tipe data dan nilai pada setiap kolom.
5. Memastikan dataset siap digunakan untuk tahap feature engineering, EDA, dan business analysis.

In [18]:
import pandas as pd 
import matplotlib.pyplot as plt 

pd.set_option('display.max_columns', None)

In [19]:
df = pd.read_csv("../Dataset/ecommerce_retail_dataset.csv")
df.head(10)

,order_id,order_date,customer_id,customer_name,customer_gender,customer_age,customer_city,customer_province,product_id,product_name,category,sub_category,unit_price,quantity,discount_percent,shipping_cost,total_amount,payment_method,order_status,delivery_date,rating
0,ORD0016487,2023-01-01,C006565,KH. Kemal Prayoga,Perempuan,23,Bontang,Kalimantan Timur,P01246,Rok Delectus Edisi Spesial,Fashion Wanita,Rok,491124,1,0,9000,491100,Transfer Bank,Selesai,2023-01-06,4.0
1,ORD0002315,2023-01-01,C007249,"Budi Siregar, S.IP",Laki-laki,29,Gianyar,Bali,P01451,Perawatan Rambut Vel Premium,Kecantikan,Perawatan Rambut,432811,2,20,12000,692500,E-Wallet,Selesai,2023-01-04,2.0
2,ORD0045934,2023-01-01,C004568,"Cut Maria Irawan, S.T.",Perempuan,50,Jakarta Utara,DKI Jakarta,P01700,Alat Tulis Doloremque Plus,Buku & Alat Tulis,Alat Tulis,71602,3,10,12000,193300,Transfer Bank,Selesai,2023-01-04,5.0
3,ORD0001080,2023-01-01,C005280,Dr. Edward Simanjuntak,Laki-laki,38,Samarinda,Kalimantan Timur,P01381,Perlengkapan Mandi Dolore Plus,Rumah Tangga,Perlengkapan Mandi,1369838,1,10,25000,1232900,E-Wallet,Selesai,2023-01-07,NaN
4,ORD0007869,2023-01-01,C010669,Shakila Wahyudin,Perempuan,52,Palembang,Sumatera Selatan,P01681,Buku Non-Fiksi Libero Premium,Buku & Alat Tulis,Buku Non-Fiksi,145639,1,20,9000,116500,Transfer Bank,Selesai,2023-01-04,5.0
5,ORD0021303,2023-01-01,C006925,Catur Simanjuntak,Laki-laki,50,Denpasar,Bali,P01289,Tas Wanita Accusantium Plus,Fashion Wanita,Tas Wanita,578646,2,0,0,1157300,QRIS,Dikembalikan,2023-01-07,NaN
6,ORD0014926,2023-01-01,C001529,Kamila Puspasari,Perempuan,53,Metro,Lampung,P01032,Laptop Dolore Premium,Elektronik,Laptop,4046830,5,15,12000,17199000,E-Wallet,Selesai,2023-01-05,4.0
7,ORD0022397,2023-01-01,C008939,Karimah Saputra,Perempuan,33,Badung,Bali,P01553,Sepeda Reiciendis Edisi Spesial,Olahraga,Sepeda,1864964,1,20,12000,1492000,COD,Diproses,NaN,NaN
8,ORD0014963,2023-01-01,C010870,Mulya Suwarno,Laki-laki,45,Badung,Bali,P01234,Blus Eum Plus,Fashion Wanita,Blus,342231,1,15,25000,290900,Transfer Bank,Selesai,2023-01-03,4.0
9,ORD0004392,2023-01-01,C011431,Darmaji Lestari,Perempuan,43,Badung,Bali,P01530,Sepatu Olahraga Iure Lite,Olahraga,Sepatu Olahraga,251509,1,5,20000,238900,Kartu Kredit,Dikembalikan,2023-01-07,NaN

1. Menghapus Data duplikat

In [20]:
df[df.duplicated(keep=False)]

,order_id,order_date,customer_id,customer_name,customer_gender,customer_age,customer_city,customer_province,product_id,product_name,category,sub_category,unit_price,quantity,discount_percent,shipping_cost,total_amount,payment_method,order_status,delivery_date,rating
335,ORD0039761,2023-01-08,C007571,"Drs. Tri Pertiwi, S.E.I",Laki-laki,44,Palembang,Sumatera Selatan,P01109,Kaos Ipsam Basic,Fashion Pria,Kaos,273777,2,10,9000,492800,E-Wallet,Selesai,2023-01-12,5.0
359,ORD0039761,2023-01-08,C007571,"Drs. Tri Pertiwi, S.E.I",Laki-laki,44,Palembang,Sumatera Selatan,P01109,Kaos Ipsam Basic,Fashion Pria,Kaos,273777,2,10,9000,492800,E-Wallet,Selesai,2023-01-12,5.0
3893,ORD0033060,2023-03-27,C001712,Aurora Megantara,Laki-laki,22,Metro,Lampung,P01102,Kaos Aliquid Lite,Fashion Pria,Kaos,555950,1,0,0,556000,COD,Dibatalkan,NaN,NaN
3897,ORD0033060,2023-03-27,C001712,Aurora Megantara,Laki-laki,22,Metro,Lampung,P01102,Kaos Aliquid Lite,Fashion Pria,Kaos,555950,1,0,0,556000,COD,Dibatalkan,NaN,NaN
4028,ORD0024513,2023-03-31,C010695,"drg. Cici Wijaya, M.Pd",Perempuan,20,Bandar Lampung,Lampung,P01552,Sepeda Sint Lite,Olahraga,Sepeda,1230456,2,5,0,2337900,Kartu Kredit,Selesai,2023-04-01,5.0
4029,ORD0024513,2023-03-31,C010695,"drg. Cici Wijaya, M.Pd",Perempuan,20,Bandar Lampung,Lampung,P01552,Sepeda Sint Lite,Olahraga,Sepeda,1230456,2,5,0,2337900,Kartu Kredit,Selesai,2023-04-01,5.0
12721,ORD0012413,2023-10-06,C009218,Lamar Yuliarti,Laki-laki,43,Mataram,Nusa Tenggara Barat,P01652,Buku Fiksi Ipsum Premium,Buku & Alat Tulis,Buku Fiksi,96694,1,5,9000,91900,COD,Selesai,2023-10-09,5.0
12747,ORD0012413,2023-10-06,C009218,Lamar Yuliarti,Laki-laki,43,Mataram,Nusa Tenggara Barat,P01652,Buku Fiksi Ipsum Premium,Buku & Alat Tulis,Buku Fiksi,96694,1,5,9000,91900,COD,Selesai,2023-10-09,5.0
13299,ORD0046837,2023-10-18,C010095,Dr. Satya Wijayanti,Perempuan,39,Bima,Nusa Tenggara Barat,P01717,Alat Tulis Architecto Lite,Buku & Alat Tulis,Alat Tulis,59877,4,10,15000,215600,COD,Diproses,NaN,NaN
13340,ORD0046837,2023-10-18,C010095,Dr. Satya Wijayanti,Perempuan,39,Bima,Nusa Tenggara Barat,P01717,Alat Tulis Architecto Lite,Buku & Alat Tulis,Alat Tulis,59877,4,10,15000,215600,COD,Diproses,NaN,NaN
16776,ORD0007190,2024-01-02,C000096,Nova Sudiati,Perempuan,19,Cilegon,Banten,P01142,Jaket Molestiae Pro,Fashion Pria,Jaket,322933,1,25,20000,242200,COD,Selesai,2024-01-08,5.0
16782,ORD0007190,2024-01-02,C000096,Nova Sudiati,Perempuan,19,Cilegon,Banten,P01142,Jaket Molestiae Pro,Fashion Pria,Jaket,322933,1,25,20000,242200,COD,Selesai,2024-01-08,5.0
22418,ORD0033255,2024-05-06,C005618,"Dr. Purwanto Waluyo, M.Kom.",Perempuan,59,Denpasar,Bali,P01397,Skincare Cum Basic,Kecantikan,Skincare,206987,1,0,15000,207000,Transfer Bank,Dikembalikan,2024-05-07,NaN
22452,ORD0033255,2024-05-06,C005618,"Dr. Purwanto Waluyo, M.Kom.",Perempuan,59,Denpasar,Bali,P01397,Skincare Cum Basic,Kecantikan,Skincare,206987,1,0,15000,207000,Transfer Bank,Dikembalikan,2024-05-07,NaN
22769,ORD0022129,2024-05-13,C002412,"R.M. Sabar Usada, S.E.",Perempuan,32,Bekasi,Jawa Barat,P01547,Sepeda Nihil Pro,Olahraga,Sepeda,2513199,1,0,12000,2513200,Kartu Kredit,Selesai,2024-05-14,4.0
22793,ORD0022129,2024-05-13,C002412,"R.M. Sabar Usada, S.E.",Perempuan,32,Bekasi,Jawa Barat,P01547,Sepeda Nihil Pro,Olahraga,Sepeda,2513199,1,0,12000,2513200,Kartu Kredit,Selesai,2024-05-14,4.0
24503,ORD0049879,2024-06-21,C010488,"Ir. Jefri Narpati, S.Gz",Perempuan,32,Malang,Jawa Timur,P01221,Blus At Edisi Spesial,Fashion Wanita,Blus,564257,1,20,0,451400,COD,Selesai,2024-06-27,NaN
24509,ORD0049879,2024-06-21,C010488,"Ir. Jefri Narpati, S.Gz",Perempuan,32,Malang,Jawa Timur,P01221,Blus At Edisi Spesial,Fashion Wanita,Blus,564257,1,20,0,451400,COD,Selesai,2024-06-27,NaN
26912,ORD0029691,2024-08-12,C000812,Qori Mustofa,Laki-laki,20,Samarinda,Kalimantan Timur,P01361,Dekorasi In Plus,Rumah Tangga,Dekorasi,693689,2,0,20000,1387400,Transfer Bank,Selesai,2024-08-15,5.0
26923,ORD0029691,2024-08-12,C000812,Qori Mustofa,Laki-laki,20,Samarinda,Kalimantan Timur,P01361,Dekorasi In Plus,Rumah Tangga,Dekorasi,693689,2,0,20000,1387400,Transfer Bank,Selesai,2024-08-15,5.0
29257,ORD0023412,2024-10-03,C006083,Mariadi Nurdiyanti,Perempuan,18,Parepare,Sulawesi Selatan,P01607,Minuman Instan Voluptas Premium,Makanan & Minuman,Minuman Instan,73842,1,0,15000,73800,Kartu Kredit,Selesai,2024-10-08,5.0
29258,ORD0023412,2024-10-03,C006083,Mariadi Nurdiyanti,Perempuan,18,Parepare,Sulawesi Selatan,P01607,Minuman Instan Voluptas Premium,Makanan & Minuman,Minuman Instan,73842,1,0,15000,73800,Kartu Kredit,Selesai,2024-10-08,5.0
29889,ORD0027729,2024-10-17,C008413,Omar Latupono,Perempuan,23,Dumai,Riau,P01690,Buku Non-Fiksi Est Basic,Buku & Alat Tulis,Buku Non-Fiksi,201353,3,5,12000,573900,Transfer Bank,Selesai,2024-10-21,4.0
29906,ORD0027729,2024-10-17,C008413,Omar Latupono,Perempuan,23,Dumai,Riau,P01690,Buku Non-Fiksi Est Basic,Buku & Alat Tulis,Buku Non-Fiksi,201353,3,5,12000,573900,Transfer Bank,Selesai,2024-10-21,4.0
38756,ORD0015821,2025-04-28,C006135,Bakidin Pangestu,Laki-laki,36,Cilegon,Banten,P01273,Sepatu Wanita Eaque Premium,Fashion Wanita,Sepatu Wanita,408690,3,20,25000,980900,E-Wallet,Selesai,2025-05-03,NaN
38763,ORD0015821,2025-04-28,C006135,Bakidin Pangestu,Laki-laki,36,Cilegon,Banten,P01273,Sepatu Wanita Eaque Premium,Fashion Wanita,Sepatu Wanita,408690,3,20,25000,980900,E-Wallet,Selesai,2025-05-03,NaN
40023,ORD0025863,2025-05-26,C004345,"R.M. Legawa Thamrin, S.T.",Perempuan,33,Kediri,Jawa Timur,P01062,Kamera Atque Lite,Elektronik,Kamera,294356,2,20,0,471000,QRIS,Diproses,NaN,NaN
40040,ORD0025863,2025-05-26,C004345,"R.M. Legawa Thamrin, S.T.",Perempuan,33,Kediri,Jawa Timur,P01062,Kamera Atque Lite,Elektronik,Kamera,294356,2,20,0,471000,QRIS,Diproses,NaN,NaN
41826,ORD0012893,2025-07-05,C007923,Lasmanto Kusumo,Perempuan,37,Mataram,Nusa Tenggara Barat,P01273,Sepatu Wanita Eaque Premium,Fashion Wanita,Sepatu Wanita,408690,1,0,9000,408700,QRIS,Dikembalikan,2025-07-06,NaN
41849,ORD0012893,2025-07-05,C007923,Lasmanto Kusumo,Perempuan,37,Mataram,Nusa Tenggara Barat,P01273,Sepatu Wanita Eaque Premium,Fashion Wanita,Sepatu Wanita,408690,1,0,9000,408700,QRIS,Dikembalikan,2025-07-06,NaN

In [21]:
data_clean = df.drop_duplicates()
data_clean.duplicated().sum()

np.int64(0)

2. Mising Value

In [22]:
data_clean.isnull().sum()

order_id                 0
order_date               0
customer_id              0
customer_name            0
customer_gender          0
customer_age             0
customer_city          500
customer_province        0
product_id               0
product_name             0
category                 0
sub_category             0
unit_price               0
quantity                 0
discount_percent         0
shipping_cost            0
total_amount             0
payment_method           0
order_status             0
delivery_date         7960
rating               18859
dtype: int64

In [23]:
data_clean[data_clean["delivery_date"].isnull()]

,order_id,order_date,customer_id,customer_name,customer_gender,customer_age,customer_city,customer_province,product_id,product_name,category,sub_category,unit_price,quantity,discount_percent,shipping_cost,total_amount,payment_method,order_status,delivery_date,rating
7,ORD0022397,2023-01-01,C008939,Karimah Saputra,Perempuan,33,Badung,Bali,P01553,Sepeda Reiciendis Edisi Spesial,Olahraga,Sepeda,1864964,1,20,12000,1492000,COD,Diproses,NaN,NaN
18,ORD0011782,2023-01-01,C006214,Paiman Wulandari,Perempuan,45,Magelang,Jawa Tengah,P01081,Audio Voluptates Basic,Elektronik,Audio,7667836,1,20,0,6134300,E-Wallet,Dibatalkan,NaN,NaN
19,ORD0043797,2023-01-01,C001225,"Nasab Mahendra, S.Psi",Perempuan,59,Bandar Lampung,Lampung,P01144,Jaket Saepe Plus,Fashion Pria,Jaket,734846,2,0,20000,1469700,E-Wallet,Dibatalkan,NaN,NaN
26,ORD0019780,2023-01-01,C000199,"Tari Firgantoro, S.E.",Perempuan,34,Bekasi,Jawa Barat,P01176,Sepatu Pria Dolorem Lite,Fashion Pria,Sepatu Pria,101226,1,15,20000,86000,COD,Diproses,NaN,NaN
37,ORD0027091,2023-01-01,C005109,Diah Wibisono,Laki-laki,58,Padang,Sumatera Barat,P01135,Celana Dolor Premium,Fashion Pria,Celana,93925,2,5,0,178500,Kartu Kredit,Dibatalkan,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,ORD0031542,2025-12-30,C010923,Elvina Puspita,Laki-laki,38,Gianyar,Bali,P01573,Snack Dolores Premium,Makanan & Minuman,Snack,148697,3,0,12000,446100,Transfer Bank,Diproses,NaN,NaN
49999,ORD0044683,2025-12-30,C011733,Padma Wahyudin,Laki-laki,35,Semarang,Jawa Tengah,P01466,Parfum Velit Plus,Kecantikan,Parfum,225157,2,15,0,382800,E-Wallet,Dibatalkan,NaN,NaN
50000,ORD0018593,2025-12-30,C011158,Galuh Pratiwi,Perempuan,22,Jakarta Selatan,DKI Jakarta,P01721,Perlengkapan Kantor Error Basic,Buku & Alat Tulis,Perlengkapan Kantor,142681,1,0,12000,142700,E-Wallet,Diproses,NaN,NaN
50009,ORD0006251,2025-12-30,C005764,Hesti Kusmawati,Laki-laki,43,Padang,Sumatera Barat,P01467,Parfum Expedita Premium,Kecantikan,Parfum,257199,5,15,12000,1093100,E-Wallet,Diproses,NaN,NaN
50011,ORD0047319,2025-12-30,C009121,"Eva Purwanti, S.Gz",Laki-laki,51,Metro,Lampung,P01571,Snack Quaerat Basic,Makanan & Minuman,Snack,108998,1,10,9000,98100,Transfer Bank,Dibatalkan,NaN,NaN

In [26]:
df.loc[
    df["delivery_date"].isna(),
    ["order_id", "order_date", "customer_id","order_status", "delivery_date"]
]

         order_id  order_date customer_id order_status delivery_date
7      ORD0022397  2023-01-01     C008939     Diproses           NaN
18     ORD0011782  2023-01-01     C006214   Dibatalkan           NaN
19     ORD0043797  2023-01-01     C001225   Dibatalkan           NaN
26     ORD0019780  2023-01-01     C000199     Diproses           NaN
37     ORD0027091  2023-01-01     C005109   Dibatalkan           NaN
...           ...         ...         ...          ...           ...
49995  ORD0031542  2025-12-30     C010923     Diproses           NaN
49999  ORD0044683  2025-12-30     C011733   Dibatalkan           NaN
50000  ORD0018593  2025-12-30     C011158     Diproses           NaN
50009  ORD0006251  2025-12-30     C005764     Diproses           NaN
50011  ORD0047319  2025-12-30     C009121   Dibatalkan           NaN

[7963 rows x 5 columns]

In [27]:
df[df["rating"].isna()]

,order_id,order_date,customer_id,customer_name,customer_gender,customer_age,customer_city,customer_province,product_id,product_name,category,sub_category,unit_price,quantity,discount_percent,shipping_cost,total_amount,payment_method,order_status,delivery_date,rating
3,ORD0001080,2023-01-01,C005280,Dr. Edward Simanjuntak,Laki-laki,38,Samarinda,Kalimantan Timur,P01381,Perlengkapan Mandi Dolore Plus,Rumah Tangga,Perlengkapan Mandi,1369838,1,10,25000,1232900,E-Wallet,Selesai,2023-01-07,NaN
5,ORD0021303,2023-01-01,C006925,Catur Simanjuntak,Laki-laki,50,Denpasar,Bali,P01289,Tas Wanita Accusantium Plus,Fashion Wanita,Tas Wanita,578646,2,0,0,1157300,QRIS,Dikembalikan,2023-01-07,NaN
7,ORD0022397,2023-01-01,C008939,Karimah Saputra,Perempuan,33,Badung,Bali,P01553,Sepeda Reiciendis Edisi Spesial,Olahraga,Sepeda,1864964,1,20,12000,1492000,COD,Diproses,NaN,NaN
9,ORD0004392,2023-01-01,C011431,Darmaji Lestari,Perempuan,43,Badung,Bali,P01530,Sepatu Olahraga Iure Lite,Olahraga,Sepatu Olahraga,251509,1,5,20000,238900,Kartu Kredit,Dikembalikan,2023-01-07,NaN
11,ORD0018599,2023-01-01,C011404,"Endra Santoso, S.T.",Perempuan,37,Bekasi,Jawa Barat,P01405,Skincare Laboriosam Premium,Kecantikan,Skincare,498082,1,10,25000,448300,Transfer Bank,Selesai,2023-01-08,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50009,ORD0006251,2025-12-30,C005764,Hesti Kusmawati,Laki-laki,43,Padang,Sumatera Barat,P01467,Parfum Expedita Premium,Kecantikan,Parfum,257199,5,15,12000,1093100,E-Wallet,Diproses,NaN,NaN
50011,ORD0047319,2025-12-30,C009121,"Eva Purwanti, S.Gz",Laki-laki,51,Metro,Lampung,P01571,Snack Quaerat Basic,Makanan & Minuman,Snack,108998,1,10,9000,98100,Transfer Bank,Dibatalkan,NaN,NaN
50012,ORD0002913,2025-12-30,C005800,Dt. Naradi Situmorang,Laki-laki,25,Bontang,Kalimantan Timur,P01581,Snack Iusto Premium,Makanan & Minuman,Snack,72173,5,15,12000,306700,Transfer Bank,Selesai,2026-01-01,NaN
50013,ORD0042555,2025-12-30,C008366,Balangga Sitompul,Perempuan,58,Magelang,Jawa Tengah,P01113,Kaos Nam Plus,Fashion Pria,Kaos,335205,1,5,0,318400,QRIS,Selesai,2026-01-01,NaN
50014,ORD0013067,2025-12-30,C011933,Ikin Pudjiastuti,Laki-laki,40,Palembang,Sumatera Selatan,P01065,Kamera Eum Plus,Elektronik,Kamera,9947444,2,0,9000,19894900,Transfer Bank,Selesai,2025-12-31,NaN

In [34]:
data_clean["customer_city"] = data_clean["customer_city"].fillna(data_clean["customer_city"].mode()[0])
data_clean["rating"] = data_clean["rating"].fillna(data_clean["rating"].median())

3. Data Type

In [54]:
data_clean["order_date"] = pd.to_datetime(df["order_date"])
data_clean["delivery_date"] = pd.to_datetime(df["delivery_date"])

4. Outlier

In [55]:
Q1 = data_clean["unit_price"].quantile(0.25)
Q3 = data_clean["unit_price"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outlier_price = data_clean[(data_clean["unit_price"] <  lower_bound) | (data_clean["unit_price"] > upper_bound)]
outlier_price

,order_id,order_date,customer_id,customer_name,customer_gender,customer_age,customer_city,customer_province,product_id,product_name,category,sub_category,unit_price,quantity,discount_percent,shipping_cost,total_amount,payment_method,order_status,delivery_date,rating
6,ORD0014926,2023-01-01,C001529,Kamila Puspasari,Perempuan,53,Metro,Lampung,P01032,Laptop Dolore Premium,Elektronik,Laptop,4046830,5,15,12000,17199000,E-Wallet,Selesai,2023-01-05,4.0
13,ORD0022010,2023-01-01,C000853,"Yusuf Kurniawan, S.E.",Perempuan,25,Makassar,Sulawesi Selatan,P01022,Laptop Eius Lite,Elektronik,Laptop,14793995,5,10,0,66573000,COD,Selesai,2023-01-07,4.0
15,ORD0006774,2023-01-01,C003539,Lega Manullang,Laki-laki,57,Gianyar,Bali,P01556,Sepeda Quo Edisi Spesial,Olahraga,Sepeda,2847824,3,5,9000,8116300,E-Wallet,Selesai,2023-01-06,5.0
17,ORD0021957,2023-01-01,C010673,"Kadir Hartati, S.Kom",Laki-laki,51,Yogyakarta,Yogyakarta,P01056,Aksesoris HP Sunt Pro,Elektronik,Aksesoris HP,14393011,4,10,15000,51814800,Kartu Kredit,Selesai,2023-01-05,4.0
18,ORD0011782,2023-01-01,C006214,Paiman Wulandari,Perempuan,45,Magelang,Jawa Tengah,P01081,Audio Voluptates Basic,Elektronik,Audio,7667836,1,20,0,6134300,E-Wallet,Dibatalkan,NaT,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49985,ORD0012311,2025-12-30,C004610,"Surya Lestari, S.IP",Perempuan,26,Magelang,Jawa Tengah,P01506,Alat Fitness Nostrum Premium,Olahraga,Alat Fitness,2961989,1,10,15000,2665800,Transfer Bank,Diproses,NaT,4.0
49991,ORD0005590,2025-12-30,C005598,Dr. Salsabila Wastuti,Laki-laki,27,Pekanbaru,Riau,P01023,Laptop Totam Pro,Elektronik,Laptop,3057360,2,20,12000,4891800,COD,Dikembalikan,2026-01-05,4.0
49992,ORD0037520,2025-12-30,C011493,Elisa Simbolon,Perempuan,46,Metro,Lampung,P01526,Sepatu Olahraga Maiores Pro,Olahraga,Sepatu Olahraga,2824067,2,10,25000,5083300,Transfer Bank,Selesai,2025-12-31,4.0
49998,ORD0025540,2025-12-30,C006817,Ophelia Nainggolan,Laki-laki,50,Sidoarjo,Jawa Timur,P01022,Laptop Eius Lite,Elektronik,Laptop,14793995,1,15,9000,12574900,Kartu Kredit,Selesai,2026-01-01,4.0
50014,ORD0013067,2025-12-30,C011933,Ikin Pudjiastuti,Laki-laki,40,Palembang,Sumatera Selatan,P01065,Kamera Eum Plus,Elektronik,Kamera,9947444,2,0,9000,19894900,Transfer Bank,Selesai,2025-12-31,4.0

In [56]:
outlier_price[
    [
        "order_id",
        "product_name",
        "category",
        "quantity",
        "unit_price",
        "total_amount"
    ]
]

,order_id,product_name,category,quantity,unit_price,total_amount
6,ORD0014926,Laptop Dolore Premium,Elektronik,5,4046830,17199000
13,ORD0022010,Laptop Eius Lite,Elektronik,5,14793995,66573000
15,ORD0006774,Sepeda Quo Edisi Spesial,Olahraga,3,2847824,8116300
17,ORD0021957,Aksesoris HP Sunt Pro,Elektronik,4,14393011,51814800
18,ORD0011782,Audio Voluptates Basic,Elektronik,1,7667836,6134300
...,...,...,...,...,...,...
49985,ORD0012311,Alat Fitness Nostrum Premium,Olahraga,1,2961989,2665800
49991,ORD0005590,Laptop Totam Pro,Elektronik,2,3057360,4891800
49992,ORD0037520,Sepatu Olahraga Maiores Pro,Olahraga,2,2824067,5083300
49998,ORD0025540,Laptop Eius Lite,Elektronik,1,14793995,12574900
50014,ORD0013067,Kamera Eum Plus,Elektronik,2,9947444,19894900

In [44]:
Q1 = data_clean["quantity"].quantile(0.25)
Q3 = data_clean["quantity"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outlier_quantity = data_clean[(data_clean["quantity"] <  lower_bound) | (data_clean["quantity"] > upper_bound)]
outlier_quantity

,order_id,order_date,customer_id,customer_name,customer_gender,customer_age,customer_city,customer_province,product_id,product_name,category,sub_category,unit_price,quantity,discount_percent,shipping_cost,total_amount,payment_method,order_status,delivery_date,rating
6,ORD0014926,2023-01-01,C001529,Kamila Puspasari,Perempuan,53,Metro,Lampung,P01032,Laptop Dolore Premium,Elektronik,Laptop,4046830,5,15,12000,17199000,E-Wallet,Selesai,2023-01-05,4.0
12,ORD0033663,2023-01-01,C006983,Edward Saragih,Laki-laki,54,Padang,Sumatera Barat,P01608,Bahan Masak Ab Edisi Spesial,Makanan & Minuman,Bahan Masak,83542,4,0,9000,334200,E-Wallet,Selesai,2023-01-08,5.0
13,ORD0022010,2023-01-01,C000853,"Yusuf Kurniawan, S.E.",Perempuan,25,Makassar,Sulawesi Selatan,P01022,Laptop Eius Lite,Elektronik,Laptop,14793995,5,10,0,66573000,COD,Selesai,2023-01-07,4.0
16,ORD0023183,2023-01-01,C003490,"Eka Palastri, S.I.Kom",Perempuan,41,Solo,Jawa Tengah,P01209,Dress Eligendi Plus,Fashion Wanita,Dress,162217,4,5,12000,616400,E-Wallet,Selesai,2023-01-06,5.0
17,ORD0021957,2023-01-01,C010673,"Kadir Hartati, S.Kom",Laki-laki,51,Yogyakarta,Yogyakarta,P01056,Aksesoris HP Sunt Pro,Elektronik,Aksesoris HP,14393011,4,10,15000,51814800,Kartu Kredit,Selesai,2023-01-05,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49984,ORD0003477,2025-12-30,C011564,"dr. Najwa Dabukke, S.Pt",Perempuan,40,Bekasi,Jawa Barat,P01017,Smartphone Eveniet Pro,Elektronik,Smartphone,11530258,5,25,9000,43238500,Kartu Kredit,Selesai,2026-01-02,4.0
50006,ORD0038286,2025-12-30,C006949,Bambang Widiastuti,Laki-laki,34,Jakarta Timur,DKI Jakarta,P01667,Buku Fiksi Quis Edisi Spesial,Buku & Alat Tulis,Buku Fiksi,175596,4,0,0,702400,E-Wallet,Selesai,2026-01-03,5.0
50007,ORD0021034,2025-12-30,C009312,Sabri Purnawati,Laki-laki,33,Bekasi,Jawa Barat,P01658,Buku Fiksi Molestiae Plus,Buku & Alat Tulis,Buku Fiksi,133099,4,10,25000,479200,Transfer Bank,Selesai,2026-01-01,4.0
50009,ORD0006251,2025-12-30,C005764,Hesti Kusmawati,Laki-laki,43,Padang,Sumatera Barat,P01467,Parfum Expedita Premium,Kecantikan,Parfum,257199,5,15,12000,1093100,E-Wallet,Diproses,NaT,4.0
50012,ORD0002913,2025-12-30,C005800,Dt. Naradi Situmorang,Laki-laki,25,Bontang,Kalimantan Timur,P01581,Snack Iusto Premium,Makanan & Minuman,Snack,72173,5,15,12000,306700,Transfer Bank,Selesai,2026-01-01,4.0

In [45]:
data_clean["quantity"].describe()

count    50000.000000
mean         1.834420
std          1.132903
min          1.000000
25%          1.000000
50%          1.000000
75%          2.000000
max          5.000000
Name: quantity, dtype: float64

In [46]:
outlier_quantity[
    [
        "order_id",
        "product_name",
        "category",
        "quantity",
        "unit_price",
        "total_amount"
    ]
]

,order_id,product_name,category,quantity,unit_price,total_amount
6,ORD0014926,Laptop Dolore Premium,Elektronik,5,4046830,17199000
12,ORD0033663,Bahan Masak Ab Edisi Spesial,Makanan & Minuman,4,83542,334200
13,ORD0022010,Laptop Eius Lite,Elektronik,5,14793995,66573000
16,ORD0023183,Dress Eligendi Plus,Fashion Wanita,4,162217,616400
17,ORD0021957,Aksesoris HP Sunt Pro,Elektronik,4,14393011,51814800
...,...,...,...,...,...,...
49984,ORD0003477,Smartphone Eveniet Pro,Elektronik,5,11530258,43238500
50006,ORD0038286,Buku Fiksi Quis Edisi Spesial,Buku & Alat Tulis,4,175596,702400
50007,ORD0021034,Buku Fiksi Molestiae Plus,Buku & Alat Tulis,4,133099,479200
50009,ORD0006251,Parfum Expedita Premium,Kecantikan,5,257199,1093100
50012,ORD0002913,Snack Iusto Premium,Makanan & Minuman,5,72173,306700

In [48]:
Q1 = data_clean["total_amount"].quantile(0.25)
Q3 = data_clean["total_amount"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outlier_amount = data_clean[(data_clean["total_amount"] <  lower_bound) | (data_clean["total_amount"] > upper_bound)]
outlier_amount

,order_id,order_date,customer_id,customer_name,customer_gender,customer_age,customer_city,customer_province,product_id,product_name,category,sub_category,unit_price,quantity,discount_percent,shipping_cost,total_amount,payment_method,order_status,delivery_date,rating
6,ORD0014926,2023-01-01,C001529,Kamila Puspasari,Perempuan,53,Metro,Lampung,P01032,Laptop Dolore Premium,Elektronik,Laptop,4046830,5,15,12000,17199000,E-Wallet,Selesai,2023-01-05,4.0
13,ORD0022010,2023-01-01,C000853,"Yusuf Kurniawan, S.E.",Perempuan,25,Makassar,Sulawesi Selatan,P01022,Laptop Eius Lite,Elektronik,Laptop,14793995,5,10,0,66573000,COD,Selesai,2023-01-07,4.0
15,ORD0006774,2023-01-01,C003539,Lega Manullang,Laki-laki,57,Gianyar,Bali,P01556,Sepeda Quo Edisi Spesial,Olahraga,Sepeda,2847824,3,5,9000,8116300,E-Wallet,Selesai,2023-01-06,5.0
17,ORD0021957,2023-01-01,C010673,"Kadir Hartati, S.Kom",Laki-laki,51,Yogyakarta,Yogyakarta,P01056,Aksesoris HP Sunt Pro,Elektronik,Aksesoris HP,14393011,4,10,15000,51814800,Kartu Kredit,Selesai,2023-01-05,4.0
18,ORD0011782,2023-01-01,C006214,Paiman Wulandari,Perempuan,45,Magelang,Jawa Tengah,P01081,Audio Voluptates Basic,Elektronik,Audio,7667836,1,20,0,6134300,E-Wallet,Dibatalkan,NaT,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49987,ORD0009588,2025-12-30,C000287,drg. Rini Latupono,Perempuan,53,Malang,Jawa Timur,P01076,Kamera Maxime Basic,Elektronik,Kamera,2157635,2,0,15000,4315300,Transfer Bank,Selesai,2026-01-04,5.0
49991,ORD0005590,2025-12-30,C005598,Dr. Salsabila Wastuti,Laki-laki,27,Pekanbaru,Riau,P01023,Laptop Totam Pro,Elektronik,Laptop,3057360,2,20,12000,4891800,COD,Dikembalikan,2026-01-05,4.0
49992,ORD0037520,2025-12-30,C011493,Elisa Simbolon,Perempuan,46,Metro,Lampung,P01526,Sepatu Olahraga Maiores Pro,Olahraga,Sepatu Olahraga,2824067,2,10,25000,5083300,Transfer Bank,Selesai,2025-12-31,4.0
49998,ORD0025540,2025-12-30,C006817,Ophelia Nainggolan,Laki-laki,50,Sidoarjo,Jawa Timur,P01022,Laptop Eius Lite,Elektronik,Laptop,14793995,1,15,9000,12574900,Kartu Kredit,Selesai,2026-01-01,4.0
50014,ORD0013067,2025-12-30,C011933,Ikin Pudjiastuti,Laki-laki,40,Palembang,Sumatera Selatan,P01065,Kamera Eum Plus,Elektronik,Kamera,9947444,2,0,9000,19894900,Transfer Bank,Selesai,2025-12-31,4.0

In [51]:
outlier_amount[
    [
        "order_id",
        "product_name",
        "category",
        "unit_price",
        "quantity",
        "discount_percent",
        "shipping_cost",
        "total_amount"
    ]
]

,order_id,product_name,category,unit_price,quantity,discount_percent,shipping_cost,total_amount
6,ORD0014926,Laptop Dolore Premium,Elektronik,4046830,5,15,12000,17199000
13,ORD0022010,Laptop Eius Lite,Elektronik,14793995,5,10,0,66573000
15,ORD0006774,Sepeda Quo Edisi Spesial,Olahraga,2847824,3,5,9000,8116300
17,ORD0021957,Aksesoris HP Sunt Pro,Elektronik,14393011,4,10,15000,51814800
18,ORD0011782,Audio Voluptates Basic,Elektronik,7667836,1,20,0,6134300
...,...,...,...,...,...,...,...,...
49987,ORD0009588,Kamera Maxime Basic,Elektronik,2157635,2,0,15000,4315300
49991,ORD0005590,Laptop Totam Pro,Elektronik,3057360,2,20,12000,4891800
49992,ORD0037520,Sepatu Olahraga Maiores Pro,Olahraga,2824067,2,10,25000,5083300
49998,ORD0025540,Laptop Eius Lite,Elektronik,14793995,1,15,9000,12574900
50014,ORD0013067,Kamera Eum Plus,Elektronik,9947444,2,0,9000,19894900

In [57]:
data_clean.info()

<class 'pandas.DataFrame'>
Index: 50000 entries, 0 to 50014
Data columns (total 21 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   order_id           50000 non-null  str
 1   order_date         50000 non-null  datetime64[us]
 2   customer_id        50000 non-null  str
 3   customer_name      50000 non-null  str
 4   customer_gender    50000 non-null  str
 5   customer_age       50000 non-null  int64
 6   customer_city      50000 non-null  str
 7   customer_province  50000 non-null  str
 8   product_id         50000 non-null  str
 9   product_name       50000 non-null  str
 10  category           50000 non-null  str
 11  sub_category       50000 non-null  str
 12  unit_price         50000 non-null  int64
 13  quantity           50000 non-null  int64
 14  discount_percent   50000 non-null  int64
 15  shipping_cost      50000 non-null  int64
 16  total_amount       50000 non-null  int64
 17  payment_method     50000 non-null  str
 18  order_status       50000 non-null  str
 19  delivery_date      42040 non-null  datetime64[us]
 20  rating             50000 non-null  float64
dtypes: datetime64[us](2), float64(1), int64(6), str(12)
memory usage: 8.4 MB

In [58]:
data_clean.to_csv("../Dataset/data_cleaning.csv", index=False)