# 3. Feature Engineering


Feature engineering dilakukan untuk membuat variabel baru yang dapat membantu proses analisis dan memberikan informasi tambahan dari data yang sudah melalui tahap data cleaning.

In [18]:
import pandas as pd 

pd.set_option('display.max_columns', None)

In [19]:
df = pd.read_csv("../Dataset/data_cleaning.csv")
df.head()

,order_id,order_date,customer_id,customer_name,customer_gender,customer_age,customer_city,customer_province,product_id,product_name,category,sub_category,unit_price,quantity,discount_percent,shipping_cost,total_amount,payment_method,order_status,delivery_date,rating
0,ORD0016487,2023-01-01,C006565,KH. Kemal Prayoga,Perempuan,23,Bontang,Kalimantan Timur,P01246,Rok Delectus Edisi Spesial,Fashion Wanita,Rok,491124,1,0,9000,491100,Transfer Bank,Selesai,2023-01-06,4.0
1,ORD0002315,2023-01-01,C007249,"Budi Siregar, S.IP",Laki-laki,29,Gianyar,Bali,P01451,Perawatan Rambut Vel Premium,Kecantikan,Perawatan Rambut,432811,2,20,12000,692500,E-Wallet,Selesai,2023-01-04,2.0
2,ORD0045934,2023-01-01,C004568,"Cut Maria Irawan, S.T.",Perempuan,50,Jakarta Utara,DKI Jakarta,P01700,Alat Tulis Doloremque Plus,Buku & Alat Tulis,Alat Tulis,71602,3,10,12000,193300,Transfer Bank,Selesai,2023-01-04,5.0
3,ORD0001080,2023-01-01,C005280,Dr. Edward Simanjuntak,Laki-laki,38,Samarinda,Kalimantan Timur,P01381,Perlengkapan Mandi Dolore Plus,Rumah Tangga,Perlengkapan Mandi,1369838,1,10,25000,1232900,E-Wallet,Selesai,2023-01-07,4.0
4,ORD0007869,2023-01-01,C010669,Shakila Wahyudin,Perempuan,52,Palembang,Sumatera Selatan,P01681,Buku Non-Fiksi Libero Premium,Buku & Alat Tulis,Buku Non-Fiksi,145639,1,20,9000,116500,Transfer Bank,Selesai,2023-01-04,5.0

1. Time Features

In [22]:
df["order_date"] = pd.to_datetime(df["order_date"])
df["delivery_date"] = pd.to_datetime(df["delivery_date"])

In [26]:
df["order_month"] = df["order_date"].dt.month
df["order_year"] = df["order_date"].dt.year
df["order_month_name"] = df["order_date"].dt.month_name()

2. Transaction Features

In [30]:
df["gross_amount"] = df["unit_price"] * df["quantity"]
df["discount_amount"] = (df["gross_amount"] * df["discount_percent"] / 100)

3. Delivery Features

In [32]:
df["delivery_days"] = (df["delivery_date"] - df["order_date"]).dt.days

4. Customer Feature

In [34]:
df["customer_age_group"] = pd.cut(
    df["customer_age"],
    bins=[0, 19, 29, 39, 49, 59, float("inf")],
    labels=["<20", "20-29", "30-39", "40-49", "50-59", "60+"]
)

In [35]:
df.head()

,order_id,order_date,customer_id,customer_name,customer_gender,customer_age,customer_city,customer_province,product_id,product_name,category,sub_category,unit_price,quantity,discount_percent,shipping_cost,total_amount,payment_method,order_status,delivery_date,rating,order_month,order_year,order_month_name,gross_amount,discount_amount,delivery_days,customer_age_group
0,ORD0016487,2023-01-01,C006565,KH. Kemal Prayoga,Perempuan,23,Bontang,Kalimantan Timur,P01246,Rok Delectus Edisi Spesial,Fashion Wanita,Rok,491124,1,0,9000,491100,Transfer Bank,Selesai,2023-01-06,4.0,1,2023,January,491124,0.0,5.0,20-29
1,ORD0002315,2023-01-01,C007249,"Budi Siregar, S.IP",Laki-laki,29,Gianyar,Bali,P01451,Perawatan Rambut Vel Premium,Kecantikan,Perawatan Rambut,432811,2,20,12000,692500,E-Wallet,Selesai,2023-01-04,2.0,1,2023,January,865622,173124.4,3.0,20-29
2,ORD0045934,2023-01-01,C004568,"Cut Maria Irawan, S.T.",Perempuan,50,Jakarta Utara,DKI Jakarta,P01700,Alat Tulis Doloremque Plus,Buku & Alat Tulis,Alat Tulis,71602,3,10,12000,193300,Transfer Bank,Selesai,2023-01-04,5.0,1,2023,January,214806,21480.6,3.0,50-59
3,ORD0001080,2023-01-01,C005280,Dr. Edward Simanjuntak,Laki-laki,38,Samarinda,Kalimantan Timur,P01381,Perlengkapan Mandi Dolore Plus,Rumah Tangga,Perlengkapan Mandi,1369838,1,10,25000,1232900,E-Wallet,Selesai,2023-01-07,4.0,1,2023,January,1369838,136983.8,6.0,30-39
4,ORD0007869,2023-01-01,C010669,Shakila Wahyudin,Perempuan,52,Palembang,Sumatera Selatan,P01681,Buku Non-Fiksi Libero Premium,Buku & Alat Tulis,Buku Non-Fiksi,145639,1,20,9000,116500,Transfer Bank,Selesai,2023-01-04,5.0,1,2023,January,145639,29127.8,3.0,50-59

In [36]:
df.to_csv("../Dataset/data_fetures.csv", index=False)